output "s3_bucket_name" {
  description = "S3 bucket name for app content"
  value       = aws_s3_bucket.kb_data.id
}

output "knowledge_base_id" {
  description = "Bedrock Knowledge Base ID"
  value       = aws_bedrockagent_knowledge_base.main.id
}

output "kb_data_source_id" {
  description = "Bedrock KB Data Source ID"
  value       = aws_bedrockagent_data_source.s3.data_source_id
}

output "agent_id" {
  description = "Bedrock Agent ID"
  value       = aws_bedrockagent_agent.main.agent_id
}

output "agent_alias_id" {
  description = "Bedrock Agent Alias ID (live)"
  value       = aws_bedrockagent_agent_alias.live.agent_alias_id
}

output "app_policy_arn" {
  description = "IAM policy ARN for the local app user"
  value       = aws_iam_policy.app_user.arn
}

output "env_local_snippet" {
  description = "Paste this into app/.env.local"
  value       = <<-EOT

    # --- AWS (generated by terraform) ---
    AWS_REGION=${var.aws_region}
    S3_BUCKET_NAME=${aws_s3_bucket.kb_data.id}
    BEDROCK_KB_ID=${aws_bedrockagent_knowledge_base.main.id}
    BEDROCK_KB_DATA_SOURCE_ID=${aws_bedrockagent_data_source.s3.data_source_id}
    BEDROCK_AGENT_ID=${aws_bedrockagent_agent.main.agent_id}
    BEDROCK_AGENT_ALIAS_ID=${aws_bedrockagent_agent_alias.live.agent_alias_id}
  EOT
}
